:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: :all
  :use_auxiliary_dependencies: TRUE
  :build_root: test_build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 1.0.1
  :default_tasks:
    - test:all

:paths:
  :test:
    - +:test
    - -:test/support
  :source:
    - Core/Src
    - -:Core/Src/freertos.c
  :include:
    - Core/Inc
    - Core/Src
  :support:
    - test/support

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_externs: :include
  :includes:
    - stm32f3xx_hal.h # Force include in mocks so types work

:plugins:
  :enabled:
    - module_generator
